### ISSUE TITLE
How to stream out the result??

### ISSUE THREAD

**Issue by dogenius01** [claygregory/node-cloudfront-log-parser#1]
Can i pipe out the parsed rows using this module?

I tried like below, but failed...

fs.createReadStream('./somelogfile.gz')
  .pipe(zlib.createGunzip())
  .pipe(parser).pipe(process.stdout);

**Comment by claygregory** [comment]
Hi @dogenius01,

Yes. Well, almost yes. Using as a stream transform, this module operates in [ObjectMode](https://nodejs.org/api/stream.html#stream_object_mode) since its purpose is to emit each row as a parsed object. `process.stdout` does not directly support consuming objects.

So:
 * The downstream Writable in your stream should also support object mode. Or,
 * Insert a transform back to a String, e.g.:
```javascript
const CloudFrontParser = require('cloudfront-log-parser');
const JsonStringify = require('streaming-json-stringify');
const fs = require('fs');
const zlib = require('zlib');

const parser = new CloudFrontParser({ format: 'web' });

fs.createReadStream('./somelogfile.gz')
  .pipe(zlib.createGunzip())
  .pipe(parser)
  .pipe(JsonStringify())
  .pipe(process.stdout);
```

**Comment by dogenius01** [comment]
Perfect. Thanks @claygregory .
